apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
  labels:
    app: customer-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: customer-api

  template:
    metadata:
      labels:
        app: customer-api

    spec:
      containers:
      - name: customer-api
        image: walmart/customer-api:1.0.0

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
